name:                flare
version:             0.1.0.0
github:              "aleksrutins/flare"
license:             BSD3
author:              "Aleks Rutins"
maintainer:          "aleks@rutins.com"
copyright:           "2023 Aleks Rutins"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aleksrutins/flare#readme>

dependencies:
- base >= 4.7 && < 5
- warp >= 3
- wai >= 3
- http-types
- wai-middleware-static >= 0.9
- wai-extra
- mtl
- text
- blaze-markup >= 0.8
- blaze-html >= 0.9
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  flare-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flare

tests:
  flare-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-haskell-fullstack

build-type: Custom